### ISSUE TITLE
Nil Point exception while trying to reach out  via Harness SDK during Terratest 

### ISSUE THREAD

**Issue by arimaverick** [harness/harness-go-sdk#119]
I am testing harness terraform module in Jenkins. I am able to perform the terraform execution part, but while reaching out to client sdk to validate few properties I am facing the following error:

```
**panic: runtime error: invalid memory address or nil pointer dereference [recovered]
              panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcef4c1]**

goroutine 19 [running]:
testing.tRunner.func1.2(0xdb4ee0, 0x1565770)
              /usr/share/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000102d80)
              /usr/share/go/src/testing/testing.go:1147 +0x4b6
panic(0xdb4ee0, 0x1565770)
              /usr/share/go/src/runtime/panic.go:965 +0x1b9
test/unit.TestHarnessK8sCloudProvider(0xc000102d80)
              **/tmp/workspace/xxxx/provider_test.go:72** +0x661
testing.tRunner(0xc000102d80, 0xf00748)
              /usr/share/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
              /usr/share/go/src/testing/testing.go:1239 +0x2b3
```

Line# 72 in the code is the following one:
`require.Equal(t, client.Configuration.AccountId, "AbcxYz1234", "FAILED: AccountID does NOT match")`

The code for client config is the following. I have set env vars HARNESSS_ACCOUNT_ID and HARNESS_API_KEY: 

```
client, _ := cd.NewClient(&cd.Config{
                             AccountId:          helpers.EnvVars.AccountId.Get(),
                             APIKey:     helpers.EnvVars.ApiKey.Get(),
                             DebugLogging: true,
              })
```

I would like to know if there is additional instruction to set network config to reach out to the harness sdk. Kindly help us to get the way forward here. 

Thank you.
@abrahamkoshy

**Comment by micahlmartin** [comment]
@arimaverick That should be working. I'm not able to reproduce this on my end.

**Comment by lukaszfedorko** [comment]
@micahlmartin I think it's due to client not initialized correctly. According to a documentation here:

https://github.com/harness/harness-go-sdk more parameters have to be passed.

Can you explain where can I get getUserAgentString()  from?
